---
- name: Provision the DigitalOcean Server
# =======================================
  hosts: localhost
  connection: local
  gather_facts: yes

  vars_prompt:
    - name: "do_region"
      prompt: >
        What region should the server be located in?
          1.  Amsterdam        (Datacenter 2)
          2.  Amsterdam        (Datacenter 3)
          3.  Frankfurt
          4.  London
          5.  New York         (Datacenter 1)
          6.  New York         (Datacenter 2)
          7.  New York         (Datacenter 3)
          8.  San Francisco
          9.  Singapore
          10. Toronto
        Please choose the number of your region. Press enter for default (#2) region.
      default: "8"
      private: no

    - name: "do_server_name"
      prompt: "\nWhat should the server be named? Press enter for default.\n"
      default: "debian-8-x64-dev"
      private: no

    - name: "do_access_token"
      prompt: "\n\nNew API access tokens can be generated in the DigitalOcean control panel.\nhttps://cloud.digitalocean.com/settings/applications\n  * When generating a new token, please note that the Write Scope is necessary\n    in order to create Droplets.\n\nWhat is your DigitalOcean Access Token?\n"
      private: no
      
    - name: "do_ssh_name"
      prompt: "\n\nThe following information can be found on your DigitalOcean control panel.\nhttps://cloud.digitalocean.com/settings/security\n\nWhat is the name of the DigitalOcean SSH key that you would like to use?\n  * If you have never uploaded an SSH key to DigitalOcean then the default\n    value will work!\n  * This key should match your .ssh/id_rsa.pub file.\n\  * DigitalOcean requires SSH keys to be unique. You cannot upload multiple\n    keys that have the same value under different names.\n\n    If you see an error that says 'SSH Key failed to be created' once the setup\n    process starts, then this is the problem. You can retry the setup process\n    using the name of the existing SSH key from the DigitalOcean control panel\n    that matches the contents of your RSA public key.\n"
      default: "mac"
      private: no

  roles:
    - digitalocean

- include: serverconfig.yml