- name: Configure the Server and install required software
# ========================================================
  hosts: digitalocean-host

  remote_user: root
  vars:
    

  roles:
    - common
    - { role: kamaln7.swapfile, swapfile_size: 1GB, swapfile_swappiness: 10, swapfile_location: /mnt/swapfile }
    - { role: geerlingguy.nodejs, nodejs_version: "5.x"}