- name: Configure the Server and install required software
# ========================================================
  hosts: digitalocean-host

  remote_user: root
  vars:
    nodejs_version: "5.x"

  roles:
    - common
    - geerlingguy.nodejs